@apiHostAddress=http://localhost:5009

POST {{apiHostAddress}}/package
Content-Type: application/json
  {
    "SenderAdress": "Jonavos g. 7, Kaunas",
	  "SenderName": "John Doe",
	  "SenderPhone": "+3709999910",
	  "RecipientAdress": "Jonavos g. 7, Kaunas",
	  "RecipientName": "Jane Doe",
	  "RecipientPhone": "+3709999920"
  }
###

@id=377652
GET http://localhost:5009/package/{{id}}

###

GET http://localhost:5009/package

###

@ids=439702
PUT http://localhost:5009/package/status/{{ids}}
Content-Type: application/json
	{
		"NewStatus": "Accepted"
	}
###
